use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let edition_slug = std::env::var("EDITION_SLUG").unwrap_or_else(|_| "zasso".to_string());

    let target_os = std::env::var("CARGO_CFG_TARGET_OS")?;
    let os_type = match target_os.as_str() {
        "macos" => "macos",
        "windows" => "windows",
        _ => "linux",
    };

    let out_dir = std::env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("generated_constants.rs");

    let content = format!(
        r#"// Auto-generated by build.rs — do not edit

#[allow(dead_code)]
pub const EDITION_SLUG: &str = "{slug}";
#[allow(dead_code)]
pub const OS_TYPE: &str = "{os}";
"#,
        slug = edition_slug,
        os = os_type,
    );

    std::fs::write(&dest_path, content)?;

    println!("cargo:rerun-if-env-changed=EDITION_SLUG");

    tauri_build::build();
    Ok(())
}
