// [::TICKET::] P3-2 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P3-2 --for-spec --no-implementation-order`.

// [::TICKET::] P0-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-6 --for-spec --no-implementation-order`.

// ============================================================================
// Initial Design Artifact — RFC-driven Implementation
// !!! NEVER DELETE OR EDIT THIS COMMENT — it is the heart of design traceability and the bloodstream of provenance information !!!
// ============================================================================
// "Node" refers to a design fragment bounded by safe I/O boundaries in the Original RFC.
//
// Graph:        ../../RFC-ROOT-GRAPH.json
// Directory:    ../../RFC-ROOT-Dirs-Tree.json
// Original RFC: ../../RFC-ROOT.md
//
// Mapped node(s):
//   - NODE_ID=N0021:  §15 M20 NativeEvent to SipEventPayload Conversion
//     → To show details: (cd ../.. && node .claude/scripts/rfc-graph/query.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md" --dirs-tree="RFC-ROOT-Dirs-Tree.json" --id=N0021 --hops=2)
//
// Full graph exploration:
//   (cd ../.. && node .claude/scripts/rfc-graph/show-graph-summary-markdown.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md")
//   (cd ../.. && node .claude/scripts/rfc-graph/query.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md" --dirs-tree="RFC-ROOT-Dirs-Tree.json" --id=Nxxxx --hops=N)
// ============================================================================
//
// [::TICKET::] P0-5: NativeEvent enum + conversion to SipEventPayload

use crate::api::event_model_payload_bus::{
    AccountId, CallId, DtmfReceivedInfo, RegistrationInfo, SipEventPayload,
};

// ── NativeEvent ─────────────────────────────────────────────────────────

/// Raw events generated by PJSIP callbacks.
///
/// These are produced by the FFI callback bridge (P0-6) and consumed by
/// `convert_native_event_to_payload()` to produce `SipEventPayload` values.
///
/// # Priority levels
/// - **P0** (implemented): Registration, Call, DTMF
/// - **P1** (future): Transport, ICE
/// - **P2** (future): CallTsx, CallRedirected, CallTransferStatus, CallReplaced, NatDetected
///
/// P1/P2 variants are declared but `convert_native_event_to_payload` returns
/// `None` for them, deferring implementation to later tickets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NativeEvent {
    // ── P0: Registration ──
    RegistrationStateChanged { acc_id: u32 },
    RegistrationStarted { acc_id: u32, renew: bool },

    // ── P0: Call ──
    CallStateChanged { call_id: u32, state: u32 },
    CallMediaStateChanged { call_id: u32 },

    // ── P0: DTMF ──
    DtmfDigit { call_id: u32, digit: char },

    // ── P1: Transport/ICE (deferred) ──
    TransportStateChanged { transport_id: u32, state: u32 },
    IceTransportError { call_id: u32 },

    // ── P2: Supplemental (deferred) ──
    CallTsxStateChanged { call_id: u32 },
    CallRedirected { call_id: u32 },
    CallTransferStatus { call_id: u32 },
    CallReplaced { call_id: u32 },
    NatDetected,
}

/// Convert a `NativeEvent` to a `SipEventPayload`.
///
/// P0 variants produce `Some(SipEventPayload)`.
/// P1/P2 variants return `None` with documented rationale.
///
/// RegistrationStateChanged follows a special pattern: it issues a
/// `RuntimeCommand::GetAccountInfo` to query registration status.
/// The actual event publication happens after the backend responds.
/// This function returns `None` for RegistrationStateChanged — the
/// caller (Reactor) must handle the GetAccountInfo flow.
///
/// # Arguments
/// * `event` - The native event to convert.
/// * `_backend` - Backend reference for API calls (used by RegistrationStateChanged).
///   Currently unused because GetAccountInfo flows through RuntimeCommand.
pub fn convert_native_event_to_payload(event: NativeEvent) -> Option<SipEventPayload> {
    match event {
        // ── P0: Registration ──
        NativeEvent::RegistrationStateChanged { .. } => {
            // RegistrationStateChanged issues RuntimeCommand::GetAccountInfo
            // and publishes after backend response. No immediate payload.
            None
        }
        NativeEvent::RegistrationStarted { acc_id, renew } => {
            // acc_id=0 is PJSUA's invalid sentinel — skip silently.
            let acc_id = AccountId::from_u64(acc_id as u64).ok()?;
            Some(SipEventPayload::RegistrationStarted(RegistrationInfo {
                account_id: acc_id,
                renew,
            }))
        }

        // ── P0: Call ──
        NativeEvent::CallStateChanged { call_id, state } => {
            let cid = CallId::from_u64(call_id as u64).ok()?;
            crate::state::m20_callstate_mapping::convert_call_state(cid, state)
        }
        NativeEvent::CallMediaStateChanged { call_id } => {
            // Without the actual pjsua_call_get_info result, default to media_status=1 (ACTIVE).
            // [::TICKET::] P3-2: ffi::bindings::pjsua_call_get_info stub available.
            // [::STUB::] P4-2: Replace with real FFI call when PJSIP library linked.
            let cid = CallId::from_u64(call_id as u64).ok()?;
            crate::state::m20_callstate_mapping::convert_call_media_state(cid, 1)
        }

        // ── P0: DTMF ──
        NativeEvent::DtmfDigit { call_id: _, digit } => {
            Some(SipEventPayload::DtmfReceived(DtmfReceivedInfo {
                digit,
                duration_ms: None,
                volume_dbm0: None,
            }))
        }

        // ── P1: Transport/ICE (deferred — returns None) ──
        NativeEvent::TransportStateChanged { .. } | NativeEvent::IceTransportError { .. } => {
            // P1: Transport/ICE events — deferred to later ticket.
            // Rationale: Transport monitoring is not required for audio-only calls.
            None
        }

        // ── P2: Supplemental (deferred — returns None) ──
        NativeEvent::CallTsxStateChanged { .. }
        | NativeEvent::CallRedirected { .. }
        | NativeEvent::CallTransferStatus { .. }
        | NativeEvent::CallReplaced { .. }
        | NativeEvent::NatDetected => {
            // P2: Supplemental events — deferred to later ticket.
            // Rationale: These events provide internal PJSIP transaction details
            // at a granularity finer than the public SipEventPayload API.
            // Consumers needing this data can use `subscribe_raw_sip()`.
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── P0 Registration ────────────────────────────────────────────────

    /// @verifies C022
    #[test]
// [::TICKET::] P0-5, P4-1 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1) --for-spec --no-implementation-order`.
    fn native_event_registration_started_maps() {
        let result = convert_native_event_to_payload(NativeEvent::RegistrationStarted {
            acc_id: 1,
            renew: false,
        });
        match result {
            Some(SipEventPayload::RegistrationStarted(info)) => {
                assert_eq!(info.account_id, AccountId::from_u64(1).unwrap());
                assert!(!info.renew);
            }
            _ => panic!("expected RegistrationStarted, got {result:?}"),
        }
    }

    /// @verifies C022
    #[test]
// [::TICKET::] P0-5, P4-1 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1) --for-spec --no-implementation-order`.
    fn native_event_registration_started_renew() {
        let result = convert_native_event_to_payload(NativeEvent::RegistrationStarted {
            acc_id: 5,
            renew: true,
        });
        match result {
            Some(SipEventPayload::RegistrationStarted(info)) => {
                assert_eq!(info.account_id, AccountId::from_u64(5).unwrap());
                assert!(info.renew);
            }
            _ => panic!("expected RegistrationStarted"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_registration_state_changed_returns_none() {
        // RegistrationStateChanged is handled via RuntimeCommand::GetAccountInfo
        // by the Reactor, not via immediate conversion.
        let result =
            convert_native_event_to_payload(NativeEvent::RegistrationStateChanged { acc_id: 1 });
        assert!(result.is_none());
    }

    // ── P0 Call ────────────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_calling() {
        let result = convert_native_event_to_payload(NativeEvent::CallStateChanged {
            call_id: 10,
            state: 1, // CALLING
        });
        assert!(matches!(result, Some(SipEventPayload::OutgoingCallStarted)));
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_confirmed() {
        let result = convert_native_event_to_payload(NativeEvent::CallStateChanged {
            call_id: 10,
            state: 3, // CONFIRMED
        });
        assert!(matches!(result, Some(SipEventPayload::CallConnected(_))));
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_disconnected() {
        let result = convert_native_event_to_payload(NativeEvent::CallStateChanged {
            call_id: 10,
            state: 4, // DISCONNECTED
        });
        assert!(matches!(result, Some(SipEventPayload::CallDisconnected)));
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_call_media_state_changed() {
        let result =
            convert_native_event_to_payload(NativeEvent::CallMediaStateChanged { call_id: 10 });
        // Currently defaults to ACTIVE (1) — stub until P0-6
        assert!(
            matches!(result, Some(SipEventPayload::MediaActive(_))),
            "expected MediaActive, got {result:?}"
        );
    }

    // ── P0 DTMF ────────────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_dtmf_digit_maps_to_received() {
        let result = convert_native_event_to_payload(NativeEvent::DtmfDigit {
            call_id: 5,
            digit: '3',
        });
        match result {
            Some(SipEventPayload::DtmfReceived(info)) => {
                assert_eq!(info.digit, '3');
            }
            _ => panic!("expected DtmfReceived"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_dtmf_digit_pound() {
        let result = convert_native_event_to_payload(NativeEvent::DtmfDigit {
            call_id: 5,
            digit: '#',
        });
        match result {
            Some(SipEventPayload::DtmfReceived(info)) => assert_eq!(info.digit, '#'),
            _ => panic!("expected DtmfReceived"),
        }
    }

    // ── P1 Transport/ICE (returns None) ────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_transport_state_changed_returns_none() {
        let result = convert_native_event_to_payload(NativeEvent::TransportStateChanged {
            transport_id: 1,
            state: 0,
        });
        assert!(result.is_none(), "P1 transport events must return None");
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_ice_transport_error_returns_none() {
        let result = convert_native_event_to_payload(NativeEvent::IceTransportError { call_id: 5 });
        assert!(result.is_none(), "P1 ICE events must return None");
    }

    // ── P2 Supplemental (returns None) ─────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_p2_variants_return_none() {
        assert!(
            convert_native_event_to_payload(NativeEvent::CallTsxStateChanged { call_id: 1 })
                .is_none()
        );
        assert!(
            convert_native_event_to_payload(NativeEvent::CallRedirected { call_id: 1 }).is_none()
        );
        assert!(
            convert_native_event_to_payload(NativeEvent::CallTransferStatus { call_id: 1 })
                .is_none()
        );
        assert!(
            convert_native_event_to_payload(NativeEvent::CallReplaced { call_id: 1 }).is_none()
        );
        assert!(convert_native_event_to_payload(NativeEvent::NatDetected).is_none());
    }

    // ── NativeEvent enum invariants ────────────────────────────────────

    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_is_clone_and_debug() {
        // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
        fn assert_cd<T: Clone + std::fmt::Debug>() {}
        assert_cd::<NativeEvent>();
    }

    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_variants_distinct() {
        let ev1 = NativeEvent::CallStateChanged {
            call_id: 1,
            state: 0,
        };
        let ev2 = NativeEvent::DtmfDigit {
            call_id: 1,
            digit: '1',
        };
        assert_ne!(format!("{ev1:?}"), format!("{ev2:?}"));
    }

    // ── Edge: zero acc_id ──────────────────────────────────────────────

    #[test]
// [::TICKET::] P0-5, P4-1 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1) --for-spec --no-implementation-order`.
    fn native_event_zero_account_id_is_skipped() {
        // acc_id=0 is PJSUA's invalid sentinel — conversion returns None.
        let result = convert_native_event_to_payload(NativeEvent::RegistrationStarted {
            acc_id: 0,
            renew: false,
        });
        assert!(result.is_none(), "zero acc_id should be skipped");
    }
}
