// [::TICKET::] P3-2 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P3-2 --for-spec --no-implementation-order`.

// [::TICKET::] P0-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-6 --for-spec --no-implementation-order`.

// ============================================================================
// Initial Design Artifact — RFC-driven Implementation
// !!! NEVER DELETE OR EDIT THIS COMMENT — it is the heart of design traceability and the bloodstream of provenance information !!!
// ============================================================================
// "Node" refers to a design fragment bounded by safe I/O boundaries in the Original RFC.
//
// Graph:        ../../RFC-ROOT-GRAPH.json
// Directory:    ../../RFC-ROOT-Dirs-Tree.json
// Original RFC: ../../RFC-ROOT.md
//
// Mapped node(s):
//   - NODE_ID=N0021:  §15 M20 NativeEvent to SipEventPayload Conversion
//     → To show details: (cd ../.. && node .claude/scripts/rfc-graph/query.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md" --dirs-tree="RFC-ROOT-Dirs-Tree.json" --id=N0021 --hops=2)
//
// Full graph exploration:
//   (cd ../.. && node .claude/scripts/rfc-graph/show-graph-summary-markdown.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md")
//   (cd ../.. && node .claude/scripts/rfc-graph/query.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md" --dirs-tree="RFC-ROOT-Dirs-Tree.json" --id=Nxxxx --hops=N)
// ============================================================================
//
// [::TICKET::] P0-5: NativeEvent enum + conversion to SipEventPayload

use crate::api::event_model_payload_bus::{
    AccountId, CallId, DtmfReceivedInfo, IncomingCallInfo, RegistrationInfo, SipEventPayload,
};
use crate::config::account_config_spec::DtmfMethod;

// ── NativeEvent ─────────────────────────────────────────────────────────

/// Raw events generated by PJSIP callbacks.
///
/// These are produced by the FFI callback bridge (P0-6) and consumed by
/// `convert_native_event_to_payload()` to produce `SipEventPayload` values.
///
/// # Priority levels
/// - **P0** (implemented): Registration, Call, DTMF
/// - **P1** (future): Transport, ICE
/// - **P2** (future): CallTsx, CallRedirected, CallTransferStatus, CallReplaced, NatDetected
///
/// P1/P2 variants are declared but `convert_native_event_to_payload` returns
/// `None` for them, deferring implementation to later tickets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NativeEvent {
    // ── P0: Registration ──
    RegistrationStateChanged {
        acc_id: u32,
    },
    RegistrationStarted {
        acc_id: u32,
        renew: bool,
    },

    // ── P0: Call ──
    /// A new incoming INVITE arrived (RFC §27.3).
    ///
    /// Carries the owning `acc_id` because an incoming call is not yet in the
    /// reactor's CallTable — the account cannot be resolved from `call_id` alone.
    IncomingCall {
        acc_id: u32,
        call_id: u32,
    },
    CallStateChanged {
        call_id: u32,
        state: u32,
    },
    CallMediaStateChanged {
        call_id: u32,
    },

    // ── P0: DTMF ──
    DtmfDigit {
        call_id: u32,
        digit: char,
    },

    // ── P1: Transport/ICE (deferred) ──
    TransportStateChanged {
        transport_id: u32,
        state: u32,
    },
    IceTransportError {
        call_id: u32,
    },

    // ── P2: Supplemental (deferred) ──
    CallTsxStateChanged {
        call_id: u32,
    },
    CallRedirected {
        call_id: u32,
    },
    CallTransferStatus {
        call_id: u32,
    },
    CallReplaced {
        call_id: u32,
    },
    NatDetected,
}

/// Convert a `NativeEvent` to a `SipEventPayload`.
///
/// P0 variants produce `Some(SipEventPayload)`.
/// P1/P2 variants produce `None` with documented rationale.
///
/// RegistrationStateChanged follows a special pattern: it issues a
/// `RuntimeCommand::GetAccountInfo` to query registration status.
/// The actual event publication happens after the backend responds.
/// RegistrationStateChanged yields `None` here — the
/// caller (Reactor) must handle the GetAccountInfo flow.
///
/// # Arguments
/// * `event` - The native event to convert.
/// * `call_account_id` - The account owning the call, resolved by the caller
///   from the call's `CallEntry`. Used by `CallStateChanged`/`CONFIRMED` so
///   `CallConnected` carries the real account; `None` for events that carry
///   their own `acc_id` (Registration) or that need no account.
pub fn convert_native_event_to_payload(
    event: NativeEvent,
    call_account_id: Option<AccountId>,
) -> Option<SipEventPayload> {
    match event {
        // ── P0: Registration ──
        NativeEvent::RegistrationStateChanged { .. } => {
            // RegistrationStateChanged issues RuntimeCommand::GetAccountInfo
            // and publishes after backend response. No immediate payload.
            None
        }
        NativeEvent::RegistrationStarted { acc_id, renew } => {
            // acc_id=0 is PJSUA's invalid sentinel — skip silently.
            let acc_id = AccountId::from_u64(acc_id as u64).ok()?;
            Some(SipEventPayload::RegistrationStarted(RegistrationInfo {
                account_id: acc_id,
                renew,
            }))
        }

        // ── P0: Call ──
        NativeEvent::IncomingCall { acc_id, call_id } => {
            // acc_id=0 is PJSUA's invalid sentinel — skip silently. caller_uri is
            // not extracted by the FFI callback (no allocation on the RT thread),
            // so the payload carries an empty URI for now (P12-8 refinement).
            let account_id = AccountId::from_u64(acc_id as u64).ok()?;
            let cid = CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::IncomingCall(IncomingCallInfo {
                call_id: cid,
                account_id,
                caller_uri: String::new(),
                caller_name: None,
            }))
        }
        NativeEvent::CallStateChanged { call_id, state } => {
            let cid = CallId::from_u64(call_id as u64).ok()?;
            crate::state::m20_callstate_mapping::convert_call_state(cid, call_account_id, state)
        }
        NativeEvent::CallMediaStateChanged { call_id } => {
            let cid = CallId::from_u64(call_id as u64).ok()?;
            // media_status always comes from pjsua_call_get_info (C110) — the
            // stub build reports NONE, the pjsua-native build reports the real
            // call media status. On an FFI failure fall back to ERROR so the
            // event bus surfaces MediaError rather than a canned success.
            let media_status = crate::ffi::bindings::resolve_call_media_status(call_id as i32)
                .unwrap_or(crate::ffi::bindings::pjsua_call_media_status::ERROR);
            crate::state::m20_callstate_mapping::convert_call_media_state(cid, media_status)
            // [::TICKET::] P5-2 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P5-2 --for-spec --no-implementation-order`.
        }

        // ── P0: DTMF ──
        NativeEvent::DtmfDigit { call_id: _, digit } => {
            // [::TICKET::] P5-2: method field added. Defaults to Rfc4733.
            // P5-3: method should come from PJSIP callback data.
            Some(SipEventPayload::DtmfReceived(DtmfReceivedInfo {
                method: DtmfMethod::Rfc4733,
                digit,
                duration_ms: None,
                volume_dbm0: None,
            }))
        }

        // ── P1: Transport/ICE (deferred — returns None) ──
        NativeEvent::TransportStateChanged { .. } | NativeEvent::IceTransportError { .. } => {
            // P1: Transport/ICE events — deferred to later ticket.
            // Rationale: Transport monitoring is not required for audio-only calls.
            None
        }

        // ── P2: Supplemental (deferred — returns None) ──
        NativeEvent::CallTsxStateChanged { .. }
        | NativeEvent::CallRedirected { .. }
        | NativeEvent::CallTransferStatus { .. }
        | NativeEvent::CallReplaced { .. }
        | NativeEvent::NatDetected => {
            // P2: Supplemental events — deferred to later ticket.
            // Rationale: These events provide internal PJSIP transaction details
            // at a granularity finer than the public SipEventPayload API.
            // Consumers needing this data can use `subscribe_raw_sip()`.
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    // P11-9: assert through the symbolic constants (real pjsua.h values), not raw
    // numbers that drift when the constant source changes.
    use crate::state::m20_callstate_mapping::pjsip_inv_state;

    /// Construct a test `CallId` from a non-zero value.
    // [::TICKET::] P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P9-6 --for-spec --no-implementation-order`.
    fn test_call_id(value: u64) -> CallId {
        CallId::from_u64(value).unwrap_or_else(|error| {
            panic!("test CallId requires a non-zero value, got {value}: {error}")
        })
    }

    /// Construct a test `AccountId` from a non-zero value.
    // [::TICKET::] P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P9-6 --for-spec --no-implementation-order`.
    fn test_account(value: u64) -> AccountId {
        AccountId::from_u64(value).unwrap_or_else(|error| {
            panic!("test AccountId requires a non-zero value, got {value}: {error}")
        })
    }

    /// Account context passed to call-event conversions in tests.
    // [::TICKET::] P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P9-6 --for-spec --no-implementation-order`.
    fn test_call_account_id() -> Option<AccountId> {
        Some(test_account(42))
    }

    // ── P0 Registration ────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P4-1, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1|P9-6) --for-spec --no-implementation-order`.
    fn native_event_registration_started_maps() {
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStarted {
                acc_id: 1,
                renew: false,
            },
            None,
        );
        match result {
            Some(SipEventPayload::RegistrationStarted(info)) => {
                assert_eq!(info.account_id, test_account(1));
                assert!(!info.renew);
            }
            _ => panic!("expected RegistrationStarted, got {result:?}"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P4-1, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1|P9-6) --for-spec --no-implementation-order`.
    fn native_event_registration_started_renew() {
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStarted {
                acc_id: 5,
                renew: true,
            },
            None,
        );
        match result {
            Some(SipEventPayload::RegistrationStarted(info)) => {
                assert_eq!(info.account_id, test_account(5));
                assert!(info.renew);
            }
            _ => panic!("expected RegistrationStarted"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_registration_state_changed_returns_none() {
        // RegistrationStateChanged is handled via RuntimeCommand::GetAccountInfo
        // by the Reactor, not via immediate conversion.
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStateChanged { acc_id: 1 },
            None,
        );
        assert!(result.is_none());
    }

    // ── P0 Call ────────────────────────────────────────────────────────

    /// @verifies C022
    #[test]
// [::TICKET::] P0-5, P9-6, P11-9, P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-9|P11-11) --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_calling() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallStateChanged {
                call_id: 10,
                state: pjsip_inv_state::CALLING,
            },
            None,
        );
        assert!(matches!(result, Some(SipEventPayload::OutgoingCallStarted)));
    }

    /// @verifies C022
    #[test]
// [::TICKET::] P0-5, P9-6, P11-9, P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-9|P11-11) --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_confirmed() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallStateChanged {
                call_id: 10,
                state: pjsip_inv_state::CONFIRMED,
            },
            test_call_account_id(),
        );
        match result {
            Some(SipEventPayload::CallConnected(info)) => {
                assert_eq!(info.account_id, test_account(42));
                assert_eq!(info.call_id, test_call_id(10));
            }
            other => panic!("expected CallConnected, got {:?}", other),
        }
    }

    /// @verifies C022
    #[test]
// [::TICKET::] P0-5, P9-6, P11-9, P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-9|P11-11) --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_disconnected() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallStateChanged {
                call_id: 10,
                state: pjsip_inv_state::DISCONNECTED,
            },
            None,
        );
        assert!(matches!(result, Some(SipEventPayload::CallDisconnected)));
    }

    /// @verifies C051
    #[test]
    // [::TICKET::] P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P11-11 --for-spec --no-implementation-order`.
    fn native_event_incoming_call_maps_to_payload() {
        let result = convert_native_event_to_payload(
            NativeEvent::IncomingCall {
                acc_id: 42,
                call_id: 7,
            },
            None,
        );
        match result {
            Some(SipEventPayload::IncomingCall(info)) => {
                assert_eq!(info.call_id, test_call_id(7));
                assert_eq!(info.account_id, test_account(42));
                assert!(info.caller_uri.is_empty());
                assert!(info.caller_name.is_none());
            }
            _ => panic!("expected IncomingCall, got {result:?}"),
        }
    }

    /// @verifies C051
    #[test]
    // [::TICKET::] P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P11-11 --for-spec --no-implementation-order`.
    fn native_event_incoming_call_zero_acc_id_skipped() {
        // acc_id=0 is PJSUA's invalid sentinel — conversion returns None.
        let result = convert_native_event_to_payload(
            NativeEvent::IncomingCall {
                acc_id: 0,
                call_id: 7,
            },
            None,
        );
        assert!(result.is_none(), "zero acc_id should be skipped");
    }

    /// @verifies C051
    #[test]
    // [::TICKET::] P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P11-11 --for-spec --no-implementation-order`.
    fn native_event_incoming_call_zero_call_id_skipped() {
        // CallId::from_u64 rejects 0 — the newtype contract surfaces as None.
        let result = convert_native_event_to_payload(
            NativeEvent::IncomingCall {
                acc_id: 42,
                call_id: 0,
            },
            None,
        );
        assert!(result.is_none(), "zero call_id should be skipped");
    }

    /// @verifies C022, C110
    #[test]
    // [::TICKET::] P0-5, P9-6, P11-10 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-10) --for-spec --no-implementation-order`.
    fn native_event_call_media_state_changed() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallMediaStateChanged { call_id: 10 },
            None,
        );
        // The handler must read media_status from pjsua_call_get_info (C110). In
        // stub mode pjsua_call_get_info writes NONE, so a correctly-wired handler
        // yields no event — never a hardcoded ACTIVE(1).
        assert!(
            result.is_none(),
            "stub media_status=NONE must yield no event, got {result:?}"
        );
    }

    // ── P0 DTMF ────────────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_dtmf_digit_maps_to_received() {
        let result = convert_native_event_to_payload(
            NativeEvent::DtmfDigit {
                call_id: 5,
                digit: '3',
            },
            None,
        );
        match result {
            Some(SipEventPayload::DtmfReceived(info)) => {
                assert_eq!(info.digit, '3');
            }
            _ => panic!("expected DtmfReceived"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_dtmf_digit_pound() {
        let result = convert_native_event_to_payload(
            NativeEvent::DtmfDigit {
                call_id: 5,
                digit: '#',
            },
            None,
        );
        match result {
            Some(SipEventPayload::DtmfReceived(info)) => assert_eq!(info.digit, '#'),
            _ => panic!("expected DtmfReceived"),
        }
    }

    // ── P1 Transport/ICE (returns None) ────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_transport_state_changed_returns_none() {
        let result = convert_native_event_to_payload(
            NativeEvent::TransportStateChanged {
                transport_id: 1,
                state: 0,
            },
            None,
        );
        assert!(result.is_none(), "P1 transport events must return None");
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_ice_transport_error_returns_none() {
        let result =
            convert_native_event_to_payload(NativeEvent::IceTransportError { call_id: 5 }, None);
        assert!(result.is_none(), "P1 ICE events must return None");
    }

    // ── P2 Supplemental (returns None) ─────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_p2_variants_return_none() {
        assert!(convert_native_event_to_payload(
            NativeEvent::CallTsxStateChanged { call_id: 1 },
            None
        )
        .is_none());
        assert!(
            convert_native_event_to_payload(NativeEvent::CallRedirected { call_id: 1 }, None)
                .is_none()
        );
        assert!(convert_native_event_to_payload(
            NativeEvent::CallTransferStatus { call_id: 1 },
            None
        )
        .is_none());
        assert!(
            convert_native_event_to_payload(NativeEvent::CallReplaced { call_id: 1 }, None)
                .is_none()
        );
        assert!(convert_native_event_to_payload(NativeEvent::NatDetected, None).is_none());
    }

    // ── NativeEvent enum invariants ────────────────────────────────────

    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_is_clone_and_debug() {
        // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
        fn assert_cd<T: Clone + std::fmt::Debug>() {}
        assert_cd::<NativeEvent>();
    }

    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_variants_distinct() {
        let ev1 = NativeEvent::CallStateChanged {
            call_id: 1,
            state: 0,
        };
        let ev2 = NativeEvent::DtmfDigit {
            call_id: 1,
            digit: '1',
        };
        assert_ne!(format!("{ev1:?}"), format!("{ev2:?}"));
    }

    // ── Edge: zero acc_id ──────────────────────────────────────────────

    #[test]
    // [::TICKET::] P0-5, P4-1, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1|P9-6) --for-spec --no-implementation-order`.
    fn native_event_zero_account_id_is_skipped() {
        // acc_id=0 is PJSUA's invalid sentinel — conversion returns None.
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStarted {
                acc_id: 0,
                renew: false,
            },
            None,
        );
        assert!(result.is_none(), "zero acc_id should be skipped");
    }
}
