// [::TICKET::] P3-2 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P3-2 --for-spec --no-implementation-order`.

// [::TICKET::] P0-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-6 --for-spec --no-implementation-order`.

// ============================================================================
// Initial Design Artifact — RFC-driven Implementation
// !!! NEVER DELETE OR EDIT THIS COMMENT — it is the heart of design traceability and the bloodstream of provenance information !!!
// ============================================================================
// "Node" refers to a design fragment bounded by safe I/O boundaries in the Original RFC.
//
// Graph:        ../../RFC-ROOT-GRAPH.json
// Directory:    ../../RFC-ROOT-Dirs-Tree.json
// Original RFC: ../../RFC-ROOT.md
//
// Mapped node(s):
//   - NODE_ID=N0021:  §15 M20 NativeEvent to SipEventPayload Conversion
//     → To show details: (cd ../.. && node .claude/scripts/rfc-graph/query.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md" --dirs-tree="RFC-ROOT-Dirs-Tree.json" --id=N0021 --hops=2)
//
// Full graph exploration:
//   (cd ../.. && node .claude/scripts/rfc-graph/show-graph-summary-markdown.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md")
//   (cd ../.. && node .claude/scripts/rfc-graph/query.js --graph="RFC-ROOT-GRAPH.json" --source="RFC-ROOT.md" --dirs-tree="RFC-ROOT-Dirs-Tree.json" --id=Nxxxx --hops=N)
// ============================================================================
//
// [::TICKET::] P0-5: NativeEvent enum + conversion to SipEventPayload

use crate::api::event_model_payload_bus::{
    AccountId, CallId, DtmfReceivedInfo, IceFailureInfo, IncomingCallInfo, RegistrationInfo,
    SipEventPayload, TransportConnectedInfo, TransportDisconnectedInfo, TransportErrorInfo,
};
use crate::config::account_config_spec::DtmfMethod;
use crate::ffi::bindings::pjsip_transport_state;

// ── NativeEvent ─────────────────────────────────────────────────────────

/// Raw events generated by PJSIP callbacks.
///
/// These are produced by the FFI callback bridge (P0-6) and consumed by
/// `convert_native_event_to_payload()` to produce `SipEventPayload` values.
///
/// # Priority levels
/// - **P0** (implemented): Registration, Call, DTMF
/// - **P1** (implemented, P16-4 §62.13): Transport, ICE
/// - **P2** (implemented, P16-4 §62.13): CallTsx, CallRedirected, CallTransferStatus, CallReplaced, NatDetected
///
/// P1/P2 variants convert to `Some(SipEventPayload)` since P16-4 §62.13.
#[derive(Debug, Clone, PartialEq, Eq)]
// [::TICKET::] P17-3 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P17-3 --for-spec --no-implementation-order`.
pub enum NativeEvent {
    // ── P0: Registration ──
    RegistrationStateChanged {
        acc_id: u32,
    },
    RegistrationStarted {
        acc_id: u32,
        renew: bool,
    },

    // ── P0: Call ──
    /// A new incoming INVITE arrived (RFC §27.3).
    ///
    /// Carries the owning `acc_id` because an incoming call is not yet in the
    /// reactor's CallTable — the account cannot be resolved from `call_id` alone.
    IncomingCall {
        acc_id: u32,
        call_id: u32,
    },
    CallStateChanged {
        call_id: u32,
        state: u32,
    },
    CallMediaStateChanged {
        call_id: u32,
    },

    // ── P0: DTMF ──
    DtmfDigit {
        call_id: u32,
        digit: char,
    },

    // ── P1: Transport/ICE (P16-4 §62.13 Some() 化) ──
    TransportStateChanged {
        transport_id: u32,
        state: u32,
    },
    IceTransportError {
        call_id: u32,
    },

    // ── P2: Supplemental (P16-4 §62.13 Some() 化) ──
    CallTsxStateChanged {
        call_id: u32,
    },
    CallRedirected {
        call_id: u32,
    },
    CallTransferStatus {
        call_id: u32,
    },
    CallReplaced {
        call_id: u32,
    },
    NatDetected,
}

/// Convert a `NativeEvent` to a `SipEventPayload`.
///
/// P0/P1/P2 variants produce `Some(SipEventPayload)` (P1/P2 since P16-4
/// §62.13). The sole exception is `RegistrationStateChanged`, which follows a
/// special pattern: it issues a `RuntimeCommand::GetAccountInfo` to query
/// registration status. The actual event publication happens after the
/// backend responds. `RegistrationStateChanged` yields `None` here — the
/// caller (Reactor) must handle the GetAccountInfo flow.
///
/// # Arguments
/// * `event` - The native event to convert.
/// * `call_account_id` - The account owning the call, resolved by the caller
///   from the call's `CallEntry`. Used by `CallStateChanged`/`CONFIRMED` so
///   `CallConnected` carries the real account; `None` for events that carry
///   their own `acc_id` (Registration) or that need no account.
// [::TICKET::] P17-3 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P17-3 --for-spec --no-implementation-order`.
pub fn convert_native_event_to_payload(
    event: NativeEvent,
    call_account_id: Option<AccountId>,
) -> Option<SipEventPayload> {
    match event {
        // ── P0: Registration ──
        NativeEvent::RegistrationStateChanged { .. } => {
            // RegistrationStateChanged issues RuntimeCommand::GetAccountInfo
            // and publishes after backend response. No immediate payload.
            None
        }
        NativeEvent::RegistrationStarted { acc_id, renew } => {
            // acc_id=0 is PJSUA's invalid sentinel — skip silently.
            let acc_id = AccountId::from_u64(acc_id as u64).ok()?;
            Some(SipEventPayload::RegistrationStarted(RegistrationInfo {
                account_id: acc_id,
                renew,
            }))
        }

        // ── P0: Call ──
        NativeEvent::IncomingCall { acc_id, call_id } => {
            // acc_id=0 is PJSUA's invalid sentinel — skip silently. caller_uri is
            // not extracted by the FFI callback (no allocation on the RT thread),
            // so the payload carries an empty URI for now (P12-8 refinement).
            let account_id = AccountId::from_u64(acc_id as u64).ok()?;
            let cid = CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::IncomingCall(IncomingCallInfo {
                call_id: cid,
                account_id,
                caller_uri: String::new(),
                caller_name: None,
            }))
        }
        NativeEvent::CallStateChanged { call_id, state } => {
            let cid = CallId::from_u64(call_id as u64).ok()?;
            crate::state::m20_callstate_mapping::convert_call_state(cid, call_account_id, state)
        }
        NativeEvent::CallMediaStateChanged { call_id } => {
            let cid = CallId::from_u64(call_id as u64).ok()?;
            // media_status always comes from pjsua_call_get_info (C110) — the
            // stub build reports NONE, the pjsua-native build reports the real
            // call media status. On an FFI failure fall back to ERROR so the
            // event bus surfaces MediaError rather than a canned success.
            let media_status = crate::ffi::bindings::resolve_call_media_status(call_id as i32)
                .unwrap_or(crate::ffi::bindings::pjsua_call_media_status::ERROR);
            crate::state::m20_callstate_mapping::convert_call_media_state(cid, media_status)
            // [::TICKET::] P5-2 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P5-2 --for-spec --no-implementation-order`.
        }

        // ── P0: DTMF ──
        NativeEvent::DtmfDigit { call_id: _, digit } => {
            // [::TICKET::] P5-2: method field added. Defaults to Rfc4733.
            // P5-3: method should come from PJSIP callback data.
            Some(SipEventPayload::DtmfReceived(DtmfReceivedInfo {
                method: DtmfMethod::Rfc4733,
                digit,
                duration_ms: None,
                volume_dbm0: None,
            }))
        }

        // ── P1: Transport/ICE (P16-4 §62.13 Some() 化) ──
        NativeEvent::TransportStateChanged {
            transport_id,
            state,
        } => {
            let (transport_type, local_addr) = resolve_transport_context(transport_id);
            match state {
                pjsip_transport_state::CONNECTED => Some(SipEventPayload::TransportConnected(
                    TransportConnectedInfo {
                        transport_type,
                        local_addr,
                        remote_addr: None,
                    },
                )),
                pjsip_transport_state::DISCONNECTED | pjsip_transport_state::SHUTDOWN => Some(
                    SipEventPayload::TransportDisconnected(TransportDisconnectedInfo {
                        transport_type,
                        local_addr,
                    }),
                ),
                other_state => Some(SipEventPayload::TransportError(TransportErrorInfo {
                    transport_type,
                    local_addr,
                    reason: format!("transport state {other_state}"),
                })),
            }
        }
        NativeEvent::IceTransportError { call_id } => {
            let cid = CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::IceNegotiationFailed(IceFailureInfo {
                call_id: cid,
                reason: String::new(),
            }))
        }

        // ── P2: Supplemental (P16-4 §62.13 Some() 化) ──
        NativeEvent::CallTsxStateChanged { call_id } => {
            CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::CallTsxStateChanged)
        }
        NativeEvent::CallRedirected { call_id } => {
            CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::CallRedirected)
        }
        NativeEvent::CallTransferStatus { call_id } => {
            CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::CallTransferStatus)
        }
        NativeEvent::CallReplaced { call_id } => {
            CallId::from_u64(call_id as u64).ok()?;
            Some(SipEventPayload::CallReplaced)
        }
        NativeEvent::NatDetected => Some(SipEventPayload::NatDetected),
    }
}

/// Resolve the transport context (type + local address) for a transport id.
///
/// The stub build has no real transport to query, so the context resolves to
/// empty defaults; the payload's variant is decided by `state`, which the
/// `pjsip_transport_state` mapping already carries. Enriching the strings via
/// `pjsua_transport_get_info` under `pjsua-native` is future work.
// [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
fn resolve_transport_context(transport_id: u32) -> (String, String) {
    let _ = transport_id;
    (String::new(), String::new())
}

#[cfg(test)]
mod tests {
    use super::*;
    // P11-9: assert through the symbolic constants (real pjsua.h values), not raw
    // numbers that drift when the constant source changes.
    use crate::ffi::bindings::pjsip_transport_state;
    use crate::state::m20_callstate_mapping::pjsip_inv_state;

    /// Construct a test `CallId` from a non-zero value.
    // [::TICKET::] P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P9-6 --for-spec --no-implementation-order`.
    fn test_call_id(value: u64) -> CallId {
        CallId::from_u64(value).unwrap_or_else(|error| {
            panic!("test CallId requires a non-zero value, got {value}: {error}")
        })
    }

    /// Construct a test `AccountId` from a non-zero value.
    // [::TICKET::] P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P9-6 --for-spec --no-implementation-order`.
    fn test_account(value: u64) -> AccountId {
        AccountId::from_u64(value).unwrap_or_else(|error| {
            panic!("test AccountId requires a non-zero value, got {value}: {error}")
        })
    }

    /// Account context passed to call-event conversions in tests.
    // [::TICKET::] P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P9-6 --for-spec --no-implementation-order`.
    fn test_call_account_id() -> Option<AccountId> {
        Some(test_account(42))
    }

    // ── P0 Registration ────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P4-1, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1|P9-6) --for-spec --no-implementation-order`.
    fn native_event_registration_started_maps() {
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStarted {
                acc_id: 1,
                renew: false,
            },
            None,
        );
        match result {
            Some(SipEventPayload::RegistrationStarted(info)) => {
                assert_eq!(info.account_id, test_account(1));
                assert!(!info.renew);
            }
            _ => panic!("expected RegistrationStarted, got {result:?}"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P4-1, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1|P9-6) --for-spec --no-implementation-order`.
    fn native_event_registration_started_renew() {
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStarted {
                acc_id: 5,
                renew: true,
            },
            None,
        );
        match result {
            Some(SipEventPayload::RegistrationStarted(info)) => {
                assert_eq!(info.account_id, test_account(5));
                assert!(info.renew);
            }
            _ => panic!("expected RegistrationStarted"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_registration_state_changed_returns_none() {
        // RegistrationStateChanged is handled via RuntimeCommand::GetAccountInfo
        // by the Reactor, not via immediate conversion.
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStateChanged { acc_id: 1 },
            None,
        );
        assert!(result.is_none());
    }

    // ── P0 Call ────────────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6, P11-9, P11-11, P12-7 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-9|P11-11|P12-7) --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_calling() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallStateChanged {
                call_id: 10,
                state: pjsip_inv_state::CALLING,
            },
            None,
        );
        assert!(matches!(result, Some(SipEventPayload::OutgoingCallStarted)));
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6, P11-9, P11-11, P12-7 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-9|P11-11|P12-7) --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_confirmed() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallStateChanged {
                call_id: 10,
                state: pjsip_inv_state::CONFIRMED,
            },
            test_call_account_id(),
        );
        match result {
            Some(SipEventPayload::CallConnected(info)) => {
                assert_eq!(info.account_id, test_account(42));
                assert_eq!(info.call_id, test_call_id(10));
            }
            other => panic!("expected CallConnected, got {:?}", other),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6, P11-9, P11-11, P12-7 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-9|P11-11|P12-7) --for-spec --no-implementation-order`.
    fn native_event_call_state_changed_disconnected() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallStateChanged {
                call_id: 10,
                state: pjsip_inv_state::DISCONNECTED,
            },
            None,
        );
        assert!(matches!(result, Some(SipEventPayload::CallDisconnected)));
    }

    /// @verifies C051
    #[test]
    // [::TICKET::] P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P11-11 --for-spec --no-implementation-order`.
    fn native_event_incoming_call_maps_to_payload() {
        let result = convert_native_event_to_payload(
            NativeEvent::IncomingCall {
                acc_id: 42,
                call_id: 7,
            },
            None,
        );
        match result {
            Some(SipEventPayload::IncomingCall(info)) => {
                assert_eq!(info.call_id, test_call_id(7));
                assert_eq!(info.account_id, test_account(42));
                assert!(info.caller_uri.is_empty());
                assert!(info.caller_name.is_none());
            }
            _ => panic!("expected IncomingCall, got {result:?}"),
        }
    }

    /// @verifies C051
    #[test]
    // [::TICKET::] P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P11-11 --for-spec --no-implementation-order`.
    fn native_event_incoming_call_zero_acc_id_skipped() {
        // acc_id=0 is PJSUA's invalid sentinel — conversion returns None.
        let result = convert_native_event_to_payload(
            NativeEvent::IncomingCall {
                acc_id: 0,
                call_id: 7,
            },
            None,
        );
        assert!(result.is_none(), "zero acc_id should be skipped");
    }

    /// @verifies C051
    #[test]
    // [::TICKET::] P11-11 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P11-11 --for-spec --no-implementation-order`.
    fn native_event_incoming_call_zero_call_id_skipped() {
        // CallId::from_u64 rejects 0 — the newtype contract surfaces as None.
        let result = convert_native_event_to_payload(
            NativeEvent::IncomingCall {
                acc_id: 42,
                call_id: 0,
            },
            None,
        );
        assert!(result.is_none(), "zero call_id should be skipped");
    }

    /// @verifies C022, C110
    #[test]
    // [::TICKET::] P0-5, P9-6, P11-10 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6|P11-10) --for-spec --no-implementation-order`.
    fn native_event_call_media_state_changed() {
        let result = convert_native_event_to_payload(
            NativeEvent::CallMediaStateChanged { call_id: 10 },
            None,
        );
        // The handler must read media_status from pjsua_call_get_info (C110). In
        // stub mode pjsua_call_get_info writes NONE, so a correctly-wired handler
        // yields no event — never a hardcoded ACTIVE(1).
        assert!(
            result.is_none(),
            "stub media_status=NONE must yield no event, got {result:?}"
        );
    }

    // ── P0 DTMF ────────────────────────────────────────────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_dtmf_digit_maps_to_received() {
        let result = convert_native_event_to_payload(
            NativeEvent::DtmfDigit {
                call_id: 5,
                digit: '3',
            },
            None,
        );
        match result {
            Some(SipEventPayload::DtmfReceived(info)) => {
                assert_eq!(info.digit, '3');
            }
            _ => panic!("expected DtmfReceived"),
        }
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P0-5, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P9-6) --for-spec --no-implementation-order`.
    fn native_event_dtmf_digit_pound() {
        let result = convert_native_event_to_payload(
            NativeEvent::DtmfDigit {
                call_id: 5,
                digit: '#',
            },
            None,
        );
        match result {
            Some(SipEventPayload::DtmfReceived(info)) => assert_eq!(info.digit, '#'),
            _ => panic!("expected DtmfReceived"),
        }
    }

    // ── P1 Transport/ICE (returns Some, P16-4 §62.13) ────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P16-4: P1 — TransportStateChanged CONNECTED → TransportConnected.
    // [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
    fn native_event_transport_state_changed_connected() {
        let result = convert_native_event_to_payload(
            NativeEvent::TransportStateChanged {
                transport_id: 1,
                state: pjsip_transport_state::CONNECTED,
            },
            None,
        );
        assert!(
            matches!(result, Some(SipEventPayload::TransportConnected(_))),
            "CONNECTED must map to TransportConnected, got {result:?}"
        );
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P16-4: P1 — TransportStateChanged DISCONNECTED → TransportDisconnected.
    // [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
    fn native_event_transport_state_changed_disconnected() {
        let result = convert_native_event_to_payload(
            NativeEvent::TransportStateChanged {
                transport_id: 1,
                state: pjsip_transport_state::DISCONNECTED,
            },
            None,
        );
        assert!(
            matches!(result, Some(SipEventPayload::TransportDisconnected(_))),
            "DISCONNECTED must map to TransportDisconnected, got {result:?}"
        );
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P16-4: P1 — any non-terminal state maps to TransportError (Some).
    // [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
    fn native_event_transport_state_changed_error_for_other_states() {
        let result = convert_native_event_to_payload(
            NativeEvent::TransportStateChanged {
                transport_id: 1,
                state: pjsip_transport_state::IDLE,
            },
            None,
        );
        assert!(
            matches!(result, Some(SipEventPayload::TransportError(_))),
            "IDLE must map to TransportError, got {result:?}"
        );
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P16-4: P1 — IceTransportError → IceNegotiationFailed (Some).
    // [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
    fn native_event_ice_transport_error_maps_to_failure() {
        let result =
            convert_native_event_to_payload(NativeEvent::IceTransportError { call_id: 5 }, None);
        match result {
            Some(SipEventPayload::IceNegotiationFailed(info)) => {
                assert_eq!(info.call_id, test_call_id(5));
            }
            other => panic!("expected IceNegotiationFailed, got {other:?}"),
        }
    }

    // ── P2 Supplemental (returns Some, P16-4 §62.13) ──────────────────

    /// @verifies C022
    #[test]
    // [::TICKET::] P16-4: P2 — all five supplemental variants convert to Some.
    // [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
    fn native_event_p2_variants_return_some() {
        assert!(matches!(
            convert_native_event_to_payload(NativeEvent::CallTsxStateChanged { call_id: 1 }, None),
            Some(SipEventPayload::CallTsxStateChanged)
        ));
        assert!(matches!(
            convert_native_event_to_payload(NativeEvent::CallRedirected { call_id: 1 }, None),
            Some(SipEventPayload::CallRedirected)
        ));
        assert!(matches!(
            convert_native_event_to_payload(NativeEvent::CallTransferStatus { call_id: 1 }, None),
            Some(SipEventPayload::CallTransferStatus)
        ));
        assert!(matches!(
            convert_native_event_to_payload(NativeEvent::CallReplaced { call_id: 1 }, None),
            Some(SipEventPayload::CallReplaced)
        ));
        assert!(matches!(
            convert_native_event_to_payload(NativeEvent::NatDetected, None),
            Some(SipEventPayload::NatDetected)
        ));
    }

    /// @verifies C022
    #[test]
    // [::TICKET::] P16-4: P2 — call_id=0 is PJSUA's invalid sentinel → None.
    // [::TICKET::] P16-4 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P16-4 --for-spec --no-implementation-order`.
    fn native_event_p2_zero_call_id_skipped() {
        assert!(
            convert_native_event_to_payload(NativeEvent::CallRedirected { call_id: 0 }, None)
                .is_none()
        );
        assert!(convert_native_event_to_payload(
            NativeEvent::CallTsxStateChanged { call_id: 0 },
            None
        )
        .is_none());
        assert!(
            convert_native_event_to_payload(NativeEvent::CallReplaced { call_id: 0 }, None)
                .is_none()
        );
    }

    // ── NativeEvent enum invariants ────────────────────────────────────

    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_is_clone_and_debug() {
        // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
        fn assert_cd<T: Clone + std::fmt::Debug>() {}
        assert_cd::<NativeEvent>();
    }

    #[test]
    // [::TICKET::] P0-5 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=P0-5 --for-spec --no-implementation-order`.
    fn native_event_variants_distinct() {
        let ev1 = NativeEvent::CallStateChanged {
            call_id: 1,
            state: 0,
        };
        let ev2 = NativeEvent::DtmfDigit {
            call_id: 1,
            digit: '1',
        };
        assert_ne!(format!("{ev1:?}"), format!("{ev2:?}"));
    }

    // ── Edge: zero acc_id ──────────────────────────────────────────────

    #[test]
    // [::TICKET::] P0-5, P4-1, P9-6 changes. Details: `node .claude/scripts/tickets/show-ticket-context.js --ticket-key=(P0-5|P4-1|P9-6) --for-spec --no-implementation-order`.
    fn native_event_zero_account_id_is_skipped() {
        // acc_id=0 is PJSUA's invalid sentinel — conversion returns None.
        let result = convert_native_event_to_payload(
            NativeEvent::RegistrationStarted {
                acc_id: 0,
                renew: false,
            },
            None,
        );
        assert!(result.is_none(), "zero acc_id should be skipped");
    }
}
