#!/usr/bin/env node
// scripts/sync-version.mjs
//
// settings.rs の APP_VERSION を唯一の情報源として、以下のファイルにバージョンを反映する：
//   - src-tauri/tauri.conf.json
//   - fe/package.json
//   - fe/src/configs/settings.ts（EDITION_SLUG, OS_TYPE も同時に生成）
//
// 環境変数:
//   EDITION_SLUG   — エディション名（デフォルト: zasso）
//   OS_TYPE        — OS 種別（デフォルト: macos）

import { readFileSync, writeFileSync } from "fs";

// ──────────────────────────────────────────────
//  Paths
// ──────────────────────────────────────────────
const SETTINGS_RS = "src-tauri/src/consts/settings.rs";
const TAURI_CONF = "src-tauri/tauri.conf.json";
const FE_PACKAGE = "fe/package.json";
const FE_SETTINGS = "fe/src/configs/settings.ts";

// ──────────────────────────────────────────────
//  Read version from settings.rs
//  settings.rs は "v0.24.236" のように v 接頭辞を含むため、
//  JSON/TS ファイルへは cleanVersion（v 無し）を書き込む。
// ──────────────────────────────────────────────
const settingsSrc = readFileSync(SETTINGS_RS, "utf-8");
const versionMatch = settingsSrc.match(
  /APP_VERSION:\s*&str\s*=\s*"(?<raw>[^"]+)"/,
);
if (!versionMatch?.groups?.raw) {
  console.error(`[sync-version] ERROR: APP_VERSION not found in ${SETTINGS_RS}`);
  process.exit(1);
}
const rawVersion = versionMatch.groups.raw;
const cleanVersion = rawVersion.replace(/^v/, "");

// ──────────────────────────────────────────────
//  Read edition / OS from environment
// ──────────────────────────────────────────────
const editionSlug = process.env.EDITION_SLUG ?? "zasso";
const osType = process.env.OS_TYPE ?? "macos";

console.log(`[sync-version] Syncing version ${rawVersion} → ${cleanVersion} …`);

// ──────────────────────────────────────────────
//  1. src-tauri/tauri.conf.json
// ──────────────────────────────────────────────
const tauriConf = JSON.parse(readFileSync(TAURI_CONF, "utf-8"));
tauriConf.version = cleanVersion;
writeFileSync(TAURI_CONF, JSON.stringify(tauriConf, null, 2) + "\n");
console.log(`  Updated ${TAURI_CONF}`);

// ──────────────────────────────────────────────
//  2. fe/package.json
// ──────────────────────────────────────────────
const fePackage = JSON.parse(readFileSync(FE_PACKAGE, "utf-8"));
fePackage.version = cleanVersion;
writeFileSync(FE_PACKAGE, JSON.stringify(fePackage, null, 2) + "\n");
console.log(`  Updated ${FE_PACKAGE}`);

// ──────────────────────────────────────────────
//  3. fe/src/configs/settings.ts
// ──────────────────────────────────────────────
const feSettings = `\
// Auto-generated by scripts/sync-version.mjs — do not edit

export const EDITION_SLUG = "${editionSlug}";
export const OS_TYPE = "${osType}";
export const APP_VERSION = "${rawVersion}";
`;
writeFileSync(FE_SETTINGS, feSettings);
console.log(`  Generated ${FE_SETTINGS}`);

console.log("[sync-version] Done.");
