#!/usr/bin/env node
// scripts/sync-version.mjs
//
// settings.rs の APP_VERSION を唯一の情報源として、以下のファイルに
// バージョンとエディションメタ情報を反映する：
//   - src-tauri/tauri.conf.json（version + productName + identifier + window title）
//   - fe/package.json（version）
//   - fe/src/configs/settings.ts（EDITION_SLUG, OS_TYPE, APP_VERSION, APP_DISPLAY_NAME）
//   - src-tauri/src/consts/settings.rs（APP_DISPLAY_NAME, APP_IDENTIFIER, APP_SLUG）
//   - src-tauri/Cargo.toml（[package] name, description）
//
// 環境変数:
//   EDITION_SLUG   — エディション名（デフォルト: zasso）
//   OS_TYPE        — OS 種別（デフォルト: macos）

import { readFileSync, writeFileSync } from "fs";

// ──────────────────────────────────────────────
//  Paths
// ──────────────────────────────────────────────
const SETTINGS_RS = "src-tauri/src/consts/settings.rs";
const TAURI_CONF = "src-tauri/tauri.conf.json";
const FE_PACKAGE = "fe/package.json";
const FE_SETTINGS = "fe/src/configs/settings.ts";
const CARGO_TOML = "src-tauri/Cargo.toml";
const EDITIONS_JSON = "editions.json";

// ──────────────────────────────────────────────
//  editions.json からカレントエディションの設定を取得
// ──────────────────────────────────────────────
function readEditionConfig(editionSlug) {
  const editions = JSON.parse(readFileSync(EDITIONS_JSON, "utf-8"));
  const entry = editions[editionSlug];
  if (!entry) {
    console.error(
      `[sync-version] ERROR: Edition '${editionSlug}' not found in ${EDITIONS_JSON}`,
    );
    process.exit(1);
  }
  return entry;
}

// ──────────────────────────────────────────────
//  settings.rs から APP_VERSION を読み取る
// ──────────────────────────────────────────────
function readVersionFromSettings() {
  const src = readFileSync(SETTINGS_RS, "utf-8");
  const match = src.match(
    /APP_VERSION:\s*&str\s*=\s*"(?<raw>[^"]+)"/,
  );
  if (!match?.groups?.raw) {
    console.error(
      `[sync-version] ERROR: APP_VERSION not found in ${SETTINGS_RS}`,
    );
    process.exit(1);
  }
  return {
    raw: match.groups.raw,
    clean: match.groups.raw.replace(/^v/, ""),
  };
}

// ──────────────────────────────────────────────
//  1. src-tauri/tauri.conf.json の更新
//  version + productName + identifier + window[0].title
// ──────────────────────────────────────────────
function updateTauriConf(version, edition) {
  const tauriConf = JSON.parse(readFileSync(TAURI_CONF, "utf-8"));
  tauriConf.version = version.clean;
  tauriConf.productName = edition.display_name;
  tauriConf.identifier = edition.identifier;
  if (tauriConf.app?.windows?.[0]) {
    tauriConf.app.windows[0].title = edition.display_name;
  }
  writeFileSync(TAURI_CONF, JSON.stringify(tauriConf, null, 2) + "\n");
  console.log(`  Updated ${TAURI_CONF}`);
}

// ──────────────────────────────────────────────
//  2. fe/package.json の更新（version のみ）
// ──────────────────────────────────────────────
function updateFePackage(version) {
  const fePackage = JSON.parse(readFileSync(FE_PACKAGE, "utf-8"));
  fePackage.version = version.clean;
  writeFileSync(FE_PACKAGE, JSON.stringify(fePackage, null, 2) + "\n");
  console.log(`  Updated ${FE_PACKAGE}`);
}

// ──────────────────────────────────────────────
//  settings.rs からウィンドウサイズ定数を読み取る
// ──────────────────────────────────────────────
function readWindowSizesFromSettings() {
  const src = readFileSync(SETTINGS_RS, "utf-8");
  const getVal = (name) =>
    src.match(new RegExp(`${name}:\\s*u16\\s*=\\s*(?<val>\\d+)`))?.groups?.val;

  const widthCollapsed = getVal("WINDOW_WIDTH_COLLAPSED");
  const heightCollapsed = getVal("WINDOW_HEIGHT_COLLAPSED");
  const widthExpanded = getVal("WINDOW_WIDTH_EXPANDED");
  const heightExpanded = getVal("WINDOW_HEIGHT_EXPANDED");

  if (!widthCollapsed || !heightCollapsed || !widthExpanded || !heightExpanded) {
    console.error(
      `[sync-version] ERROR: Window size constants not found in ${SETTINGS_RS}`,
    );
    process.exit(1);
  }

  return { widthCollapsed, heightCollapsed, widthExpanded, heightExpanded };
}

// ──────────────────────────────────────────────
//  3. fe/src/configs/settings.ts の更新
//  EDITION_SLUG, OS_TYPE, APP_VERSION, APP_DISPLAY_NAME, WINDOW_* 定数
// ──────────────────────────────────────────────
function updateFeSettings(version, edition, editionSlug, osType, windowSizes) {
  const feSettings = `\
// Auto-generated by scripts/sync-version.mjs — do not edit

export const EDITION_SLUG = "${editionSlug}";
export const OS_TYPE = "${osType}";
export const APP_VERSION = "${version.raw}";
export const APP_DISPLAY_NAME = "${edition.display_name}";

// ウィンドウサイズ設定（src-tauri/src/consts/settings.rs から同期）
export const WINDOW_WIDTH_COLLAPSED = ${windowSizes.widthCollapsed};
export const WINDOW_HEIGHT_COLLAPSED = ${windowSizes.heightCollapsed};
export const WINDOW_WIDTH_EXPANDED = ${windowSizes.widthExpanded};
export const WINDOW_HEIGHT_EXPANDED = ${windowSizes.heightExpanded};
`;
  writeFileSync(FE_SETTINGS, feSettings);
  console.log(`  Generated ${FE_SETTINGS}`);
}

// ──────────────────────────────────────────────
//  4. src-tauri/src/consts/settings.rs の更新
//  APP_DISPLAY_NAME, APP_IDENTIFIER, APP_SLUG
// ──────────────────────────────────────────────
function updateSettingsRs(edition) {
  let src = readFileSync(SETTINGS_RS, "utf-8");

  // APP_DISPLAY_NAME を editions.json の値で上書き
  src = src.replace(
    /(APP_DISPLAY_NAME:\s*&str\s*=\s*")[^"]*(")/,
    `$1${edition.display_name}$2`,
  );

  // APP_IDENTIFIER が既に存在すれば上書き、なければ追加
  if (src.includes("APP_IDENTIFIER")) {
    src = src.replace(
      /(APP_IDENTIFIER:\s*&str\s*=\s*")[^"]*(")/,
      `$1${edition.identifier}$2`,
    );
  } else {
    src = src.replace(
      /(pub\(crate\) const APP_DISPLAY_NAME[^\n]*)/,
      `$1\n\n/// アプリケーション識別子（バンドルID）\npub(crate) const APP_IDENTIFIER: &str = "${edition.identifier}";`,
    );
  }

  // APP_SLUG が既に存在すれば上書き、なければ追加
  if (src.includes("APP_SLUG")) {
    src = src.replace(
      /(APP_SLUG:\s*&str\s*=\s*")[^"]*(")/,
      `$1${edition.slug}$2`,
    );
  } else {
    src = src.replace(
      /(pub\(crate\) const APP_IDENTIFIER[^\n]*)/,
      `$1\n\n/// アプリケーションスラッグ\npub(crate) const APP_SLUG: &str = "${edition.slug}";`,
    );
  }

  writeFileSync(SETTINGS_RS, src);
  console.log(`  Updated ${SETTINGS_RS}`);
}

// ──────────────────────────────────────────────
//  5. src-tauri/Cargo.toml の更新
//  [package] name = slug, description = app_caption
// ──────────────────────────────────────────────
function updateCargoToml(edition) {
  let src = readFileSync(CARGO_TOML, "utf-8");

  // [package] name をエディション slug に書き換え
  src = src.replace(
    /^(name\s*=\s*")[^"]*(")/m,
    `$1${edition.slug}$2`,
  );

  // [package] description を editions.json の app_caption に書き換え
  src = src.replace(
    /^(description\s*=\s*")[^"]*(")/m,
    `$1${edition.app_caption}$2`,
  );

  writeFileSync(CARGO_TOML, src);
  console.log(`  Updated ${CARGO_TOML}`);
}

// ──────────────────────────────────────────────
//  エントリポイント
// ──────────────────────────────────────────────
const editionSlug = process.env.EDITION_SLUG ?? "zasso";
const osType = process.env.OS_TYPE ?? "macos";
const version = readVersionFromSettings();
const edition = readEditionConfig(editionSlug);

console.log(
  `[sync-version] Syncing ${editionSlug} ${version.raw} (${osType}) …`,
);

updateTauriConf(version, edition);
updateFePackage(version);

const windowSizes = readWindowSizesFromSettings();
updateFeSettings(version, edition, editionSlug, osType, windowSizes);

updateSettingsRs(edition);
updateCargoToml(edition);

console.log("[sync-version] Done.");
